/**
 * Copyright 2015 Jamie Mansfield <https://github.com/lexware>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.lexware.canarymavenplugin;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

@Mojo(name = "createconfig", defaultPhase = LifecyclePhase.PACKAGE, requiresProject = true)
public class CanaryMavenPlugin extends AbstractMojo {
    @Parameter(defaultValue = "${groupId}.${artifactId}.${project.name}Plugin", required = true)
    private String mainClass;
    
    @Parameter(defaultValue = "${project.name}", required = true)
    private String name;
    
    @Parameter(defaultValue = "${project.version}", required = true)
    private String version;
    
    @Parameter(required = true)
    private String author;
    
    @Parameter(defaultValue = "java", required = false)
    private String language;
    
    @Parameter(defaultValue = "false", required = false)
    private Boolean enableEarly;
    
    @Parameter(required = false)
    private String dependencies;

    @Parameter(defaultValue = "${project.build.outputDirectory}", required = true)
    private File outputDirectory;

    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        getLog().info("=============== canary-maven-plugin ===============");
        getLog().info("Licensed under the Apache License version 2.");
        getLog().info("Created by Jamie Mansfield <https://github.com/lexware>");
        getLog().info("===================================================");

        Properties props = new Properties();
        props.put("main-class", mainClass);
        props.put("name", name);
        props.put("version", version);
        props.put("author", author);
        if(language != null) props.put("language", language);
        if(enableEarly != null) props.put("enableEarly", enableEarly);
        if(dependencies != null) props.put("dependencies", dependencies);

        try {
            FileOutputStream fos = new FileOutputStream(new File(outputDirectory, "Canary.inf"));
            props.store(fos, "Generated by canary-maven-plugin");
            fos.flush();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
